### PR TITLE
[Improve-#10][adm] GESD need to check compatibility

### PR DESCRIPTION
**Pull request by yangtao2014**

### CODE REVIEW

**Comment by algorithm-tools** [comment]
Issues: Issue #10

**Comment by algorithm-tools** [comment]
The K-S test is a good method, but it can be somewhat limited in its use, and it is more suited to tests of normal distributions with large sample sizes. For small sample data, the K-S test is less statistically valid and prone to false negative results.
Are there other tests that complement or replace the K-S test?

**Comment by algorithm-tools** [comment]
As far as I know, there are also Shapiro-Wilk test, Anderson-Darling test (improved version of K-S), their differences are as follows:
- Kolmogorov-Smirnov (K-S) test: suitable for large samples, goodness-of-fit tests for a variety of distributions, but insensitive to the tails of the distribution and less statistically valid with small samples.
- Shapiro-Wilk test: suitable for small samples, good under small samples, but only applicable to normality tests, overly sensitive to large samples.
- Anderson-Darling test: improved K-S test, sensitive to the tails of the distribution, suitable for a wide range of distributions, and has good statistical validity in both small and large samples.

Here we only need to test the normal distribution, may be the main consideration is the sample size, may be most of the application scenarios in the smaller sample size situation (due to the general requirements of the business of the higher timeliness, there may only be a small number of samples for anomaly monitoring), of course, for the sake of functionality, but also need to take into account the situation of larger samples.

Do you have any other ideas?

**Comment by yangtao2014** [comment]
> The K-S test is a good method, but it can be somewhat limited in its use, and it is more suited to tests of normal distributions with large sample sizes. For small sample data, the K-S test is less statistically valid and prone to false negative results. Are there other tests that complement or replace the K-S test?

**The following are common：**
- Kolmogorov-Smirnov test
- Cramer-von Mises test
- Anderson–Darling test
- Shapiro–Wilk test

The applicable scenarios of each test method have to do further simulation experiments to draw conclusions, and the better implementation of Java is currently K-S test

**Comment by yangtao2014** [comment]
> As far as I know, there are also Shapiro-Wilk test, Anderson-Darling test (improved version of K-S), their differences are as follows:
> 
> * Kolmogorov-Smirnov (K-S) test: suitable for large samples, goodness-of-fit tests for a variety of distributions, but insensitive to the tails of the distribution and less statistically valid with small samples.
> * Shapiro-Wilk test: suitable for small samples, good under small samples, but only applicable to normality tests, overly sensitive to large samples.
> * Anderson-Darling test: improved K-S test, sensitive to the tails of the distribution, suitable for a wide range of distributions, and has good statistical validity in both small and large samples.
> 
> Here we only need to test the normal distribution, may be the main consideration is the sample size, may be most of the application scenarios in the smaller sample size situation (due to the general requirements of the business of the higher timeliness, there may only be a small number of samples for anomaly monitoring), of course, for the sake of functionality, but also need to take into account the situation of larger samples.
> 
> Do you have any other ideas?

If the amount of data is relatively small, the default data meets the normal distribution, and so the amount of data is relatively large, before using the K-S test, the other tests lack of data simulation experiments, can not confirm that they are in a small amount of data better than the K-S test, but from the point of view of the realizability of the current implementation of the Java K-S test is still relatively good to achieve, the other tests are more time-consuming to implement in Java, can be put into the next version to realize

**Comment by algorithm-tools** [comment]
> > As far as I know, there are also Shapiro-Wilk test, Anderson-Darling test (improved version of K-S), their differences are as follows:
> > 
> > * Kolmogorov-Smirnov (K-S) test: suitable for large samples, goodness-of-fit tests for a variety of distributions, but insensitive to the tails of the distribution and less statistically valid with small samples.
> > * Shapiro-Wilk test: suitable for small samples, good under small samples, but only applicable to normality tests, overly sensitive to large samples.
> > * Anderson-Darling test: improved K-S test, sensitive to the tails of the distribution, suitable for a wide range of distributions, and has good statistical validity in both small and large samples.
> > 
> > Here we only need to test the normal distribution, may be the main consideration is the sample size, may be most of the application scenarios in the smaller sample size situation (due to the general requirements of the business of the higher timeliness, there may only be a small number of samples for anomaly monitoring), of course, for the sake of functionality, but also need to take into account the situation of larger samples.
> > Do you have any other ideas?
> 
> If the amount of data is relatively small, the default data meets the normal distribution, and so the amount of data is relatively large, before using the K-S test, the other tests lack of data simulation experiments, can not confirm that they are in a small amount of data better than the K-S test, but from the point of view of the realizability of the current implementation of the Java K-S test is still relatively good to achieve, the other tests are more time-consuming to implement in Java, can be put into the next version to realize

It's a viable approach.

**Comment by algorithm-tools** [comment]
LGTM

**Pull request merged**
